"""
Django settings for core project.

Generated by 'django-admin startproject' using Django 6.0.3.

For more information on this file, see
https://docs.djangoproject.com/en/6.0/topics/settings/

For the full list of settings and their values, see
https://docs.djangoproject.com/en/6.0/ref/settings/
"""

import environ
import os
from pathlib import Path
import sys

# 1. Initialize environ
env = environ.Env(
    DEBUG=(bool, False),
    HTTP_TIMEOUT_SECONDS=(float, 10.0),
)

# Build paths inside the project like this: BASE_DIR / 'subdir'.
BASE_DIR = Path(__file__).resolve().parent.parent

# 2. Read the .env file
environ.Env.read_env(os.path.join(BASE_DIR, ".env"))


# Quick-start development settings - unsuitable for production
# See https://docs.djangoproject.com/en/6.0/howto/deployment/checklist/
env = environ.Env(
    # set casting, default value
    DEBUG=(bool, True),
)

# SECURITY WARNING: keep the secret key used in production secret!
# SECRET_KEY = 'django-insecure-w5a(vext8be&x!r@xnixc^48q98+5gogj=wa_3tl-490g*qhdm'

# SECURITY WARNING: don't run with debug turned on in production!
# DEBUG = True

SECRET_KEY = env("SECRET_KEY")

DEBUG = env("DEBUG")

# --- Celery (NEW) ---
CELERY_BROKER_URL = env("CELERY_BROKER_URL", default="redis://localhost:6379/0")
CELERY_RESULT_BACKEND = env("CELERY_RESULT_BACKEND", default=CELERY_BROKER_URL)

# Don’t store huge results; we just enqueue work.
CELERY_TASK_IGNORE_RESULT = True
CELERY_TASK_TRACK_STARTED = True

ALLOWED_HOSTS = []


# Application definition

INSTALLED_APPS = [
    "django.contrib.admin",
    "django.contrib.auth",
    "django.contrib.contenttypes",
    "django.contrib.sessions",
    "django.contrib.messages",
    "django.contrib.staticfiles",
    "rest_framework",
    "drf_spectacular",
    "django_filters",
    "apps.customers",
    "apps.supports",
]

MIDDLEWARE = [
    "django.middleware.security.SecurityMiddleware",
    "django.contrib.sessions.middleware.SessionMiddleware",
    "django.middleware.common.CommonMiddleware",
    "django.middleware.csrf.CsrfViewMiddleware",
    "django.contrib.auth.middleware.AuthenticationMiddleware",
    "django.contrib.messages.middleware.MessageMiddleware",
    "django.middleware.clickjacking.XFrameOptionsMiddleware",
]

ROOT_URLCONF = "core.urls"

TEMPLATES = [
    {
        "BACKEND": "django.template.backends.django.DjangoTemplates",
        "DIRS": [],
        "APP_DIRS": True,
        "OPTIONS": {
            "context_processors": [
                "django.template.context_processors.request",
                "django.contrib.auth.context_processors.auth",
                "django.contrib.messages.context_processors.messages",
            ],
        },
    },
]

WSGI_APPLICATION = "core.wsgi.application"


# Database
# https://docs.djangoproject.com/en/6.0/ref/settings/#databases
SQLITE_DB_CONFIG = {
    "ENGINE": "django.db.backends.sqlite3",
    "NAME": BASE_DIR / "db.sqlite3",
}

POSTGRES_DB_CONFIG = {
    "ENGINE": "django.db.backends.postgresql",
    "NAME": env("PG_DB_NAME"),
    "USER": env("PG_DB_USER"),
    "PASSWORD": env("PG_DB_PASSWORD"),
    "HOST": env("PG_DB_HOST"),
    "PORT": env("PG_DB_PORT", cast=int),
    "OPTIONS": {
        "sslmode": "prefer",  # Use 'require' if SSL is enforced
    },
}

DATABASES = {"default": POSTGRES_DB_CONFIG}


# Password validation
# https://docs.djangoproject.com/en/6.0/ref/settings/#auth-password-validators

AUTH_PASSWORD_VALIDATORS = [
    {
        "NAME": "django.contrib.auth.password_validation.UserAttributeSimilarityValidator",
    },
    {
        "NAME": "django.contrib.auth.password_validation.MinimumLengthValidator",
    },
    {
        "NAME": "django.contrib.auth.password_validation.CommonPasswordValidator",
    },
    {
        "NAME": "django.contrib.auth.password_validation.NumericPasswordValidator",
    },
]

REST_FRAMEWORK = {
    # ...
    "DEFAULT_FILTER_BACKENDS": [
        "django_filters.rest_framework.DjangoFilterBackend",
    ],
    "DEFAULT_SCHEMA_CLASS": "drf_spectacular.openapi.AutoSchema",
    "DEFAULT_PAGINATION_CLASS": "apps.base.pagination.StandardResultsSetPagination",
    "PAGE_SIZE": 10,
}

# Optional: Add basic info for your Swagger UI
SPECTACULAR_SETTINGS = {
    "TITLE": "Customer Activity API",
    "DESCRIPTION": "API documentation for the Customer Activity project",
    "VERSION": "1.0.0",
    "SERVE_INCLUDE_SCHEMA": False,
}


# Internationalization
# https://docs.djangoproject.com/en/6.0/topics/i18n/

LANGUAGE_CODE = "en-us"

TIME_ZONE = "UTC"

USE_I18N = True

USE_TZ = True


# Static files (CSS, JavaScript, Images)
# https://docs.djangoproject.com/en/6.0/howto/static-files/

STATIC_URL = "static/"

if "test" in sys.argv:
    DATABASES = {"default": SQLITE_DB_CONFIG}
