# Generated by Django 6.0.3 on 2026-03-15 13:48

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('customers', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Activity',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('external_id', models.BigIntegerField()),
                ('source', models.CharField(choices=[('crm', 'crm'), ('support', 'support')], max_length=20)),
                ('type', models.CharField(choices=[('ticket', 'ticket'), ('note', 'note'), ('event', 'event')], max_length=20)),
                ('title', models.CharField(blank=True, default='', max_length=255)),
                ('content', models.TextField(blank=True, default='')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('customer', models.ForeignKey(blank=True, help_text='May be null if the external system references an unknown customer.', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='activities', to='customers.customer')),
            ],
            options={
                'constraints': [models.UniqueConstraint(fields=('source', 'external_id'), name='uniq_activity_source_external_id')],
            },
        ),
    ]
