# Generated by Django 6.0.3 on 2026-03-15 21:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('supports', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='activity',
            name='ai_category',
            field=models.CharField(blank=True, default='', max_length=50),
        ),
        migrations.AddField(
            model_name='activity',
            name='ai_priority',
            field=models.CharField(blank=True, default='', max_length=20),
        ),
        migrations.AddField(
            model_name='activity',
            name='ai_summary',
            field=models.TextField(blank=True, default=''),
        ),
    ]
